import {describe,it,expect,vi,beforeEach} from 'vitest';
const mocks=vi.hoisted(()=>({put:vi.fn(),acquire:vi.fn(),release:vi.fn()}));
vi.mock('../src/pg-edit-session.js',()=>({acquirePgScopeAccessLease:mocks.acquire,releasePgScopeAccessLease:mocks.release,resolvePgEditWorkspaceContext:s=>({workspaceId:s.workspaceId,baseUrl:'http://tower',appNpub:'app'})}));
vi.mock('../src/tower-command-intents.js',()=>({putTowerPgScopeAccess:mocks.put}));
vi.mock('../src/pg-read-hydrator.js',()=>({resolveTowerPgWorkspaceContext:s=>({workspaceId:s.workspaceId,baseUrl:'http://tower',appNpub:'app'})}));
import {scopeAccessManagerMixin as mixin,SCOPE_ACCESS_ROLES} from '../src/scope-access-manager.js';
function store() {const s={...mixin,workspaceId:'workspace',isTowerPgMode:true,pgWorkspaceMembers:[{actor_id:'human',kind:'human',display_name:'Person'},{actor_id:'agent',kind:'agent',display_name:'Agent'}],pgChannelGrantGroupOptions:[{groupId:'group',label:'Builders'}],getPgWorkspaceMemberLabel:m=>m.display_name,getTowerSyncService:()=>({ensureLoaded:vi.fn(async()=>({can_manage:true,revision:'v1',grants:[],effective_access:[]}))})};Object.defineProperties(s,Object.getOwnPropertyDescriptors(mixin));return s;}
describe('Scope Access',()=>{
 beforeEach(()=>{vi.resetAllMocks();mocks.acquire.mockResolvedValue({id:'lease',lease_token:'token'});mocks.release.mockResolvedValue(undefined);mocks.put.mockResolvedValue({can_manage:true,revision:'new',grants:[],effective_access:[]});});
 it('searches people, agents and canonical groups together with stable IDs and roles',()=>{const s=store();expect(s.scopeAccessCandidates.map(p=>[p.id,p.label,p.type,p.kind])).toEqual([['human','Person','actor','human'],['agent','Agent','actor','agent'],['group','Builders','group','group']]);s.changeScopeAccessQuery('build');expect(s.scopeAccessSearchResults.map(p=>p.id)).toEqual(['group']);expect(SCOPE_ACCESS_ROLES.map(r=>r.label)).toEqual(['Context editor','Scope manager']);});
 it('uses management-only canonical choices without extra directory authority',()=>{const s=store();s.scopeAccessData={principals:{actors:[{id:'scoped-agent',kind:'agent',label:'Scoped agent'}],groups:[{id:'builders',label:'Builders'}]}};expect(s.scopeAccessCandidates.map(p=>p.id)).toEqual(['scoped-agent','builders']);});
 it('hydrates missing names asynchronously without changing stable selected identity or canonical names',async()=>{const s=store();let name='npub1profile';s.getSenderName=()=>name;s.resolveChatProfile=vi.fn(async()=>{await Promise.resolve();name='Resolved person'});s.scopeAccessData={principals:{actors:[{id:'missing',npub:'npub1profile',kind:'human',label:'Unnamed person'},{id:'named',npub:'npub1canonical',kind:'human',label:'Canonical person'}],groups:[]}};s.selectScopeAccessPrincipal(s.scopeAccessCandidates[0]);expect(s.scopeAccessSelectedPrincipal.label).toBe('Unnamed person');s.hydrateScopeAccessNames();await Promise.resolve();await Promise.resolve();expect(s.scopeAccessSelectedPrincipal.id).toBe('missing');expect(s.scopeAccessSelectedPrincipal.label).toBe('Resolved person');expect(s.scopeAccessCandidates[1].label).toBe('Canonical person');expect(s.resolveChatProfile).toHaveBeenCalledWith('npub1profile');});
 it('distinguishes duplicate names, rejects typed-only IDs and prevents duplicate direct roles',async()=>{const s=store();s.scopeAccessScope={record_id:'scope'};s.scopeAccessWorkspaceId='workspace';s.scopeAccessData={can_manage:true,revision:'rev',principals:{actors:[{id:'one',kind:'human',label:'Same'},{id:'two',kind:'human',label:'Same'}],groups:[{id:'group',label:'Same'}]},grants:[{principal_id:'one',principal_type:'actor',role:'context_editor',permissions:['context.edit']}]};expect(s.scopeAccessCandidates[0].subtitle).toContain('1 of 2');expect(s.scopeAccessPrincipalSubtitle({principal_id:'one',principal_type:'actor',kind:'human'})).toContain('1 of 2');s.changeScopeAccessQuery('one');await s.saveScopeAccess();expect(mocks.put).not.toHaveBeenCalled();s.selectScopeAccessPrincipal(s.scopeAccessCandidates[0]);expect(s.scopeAccessAlreadyGranted).toBe(true);await s.saveScopeAccess();expect(mocks.put).not.toHaveBeenCalled();s.selectScopeAccessPrincipal(s.scopeAccessCandidates[2]);s.scopeAccessRole='scope_manager';await s.saveScopeAccess();expect(mocks.put).toHaveBeenCalledWith(s,'workspace','scope',expect.objectContaining({principal_type:'group',principal_id:'group',role:'scope_manager'}),expect.any(Object));});
 it('uses current revision and scope lease; reader cannot issue commands',async()=>{const s=store();s.scopeAccessScope={record_id:'scope'};s.scopeAccessWorkspaceId='workspace';s.scopeAccessData={can_manage:false};await s.saveScopeAccess();expect(mocks.put).not.toHaveBeenCalled();s.scopeAccessData={can_manage:true,revision:'rev'};s.scopeAccessPrincipalId='agent';s.scopeAccessPrincipalKind='agent';mocks.acquire.mockResolvedValue({id:'lease',lease_token:'token'});mocks.release.mockResolvedValue(undefined);mocks.put.mockResolvedValue({can_manage:true,revision:'new'});await s.saveScopeAccess();expect(mocks.put).toHaveBeenCalledWith(s,'workspace','scope',expect.objectContaining({principal_type:'actor',principal_id:'agent',role:'context_editor',expected_revision:'rev',lease_token:'token'}),expect.any(Object));expect(mocks.release).toHaveBeenCalled();});
 it('surfaces conflict without claiming save and releases lease',async()=>{mocks.put.mockRejectedValue({status:409});const s=store();s.scopeAccessScope={record_id:'scope'};s.scopeAccessWorkspaceId='workspace';s.scopeAccessData={can_manage:true,revision:'rev'};s.scopeAccessPrincipalId='human';await s.saveScopeAccess();expect(s.scopeAccessError).toContain('Refresh');expect(s.scopeAccessNotice).toBe('');});
});
