import {describe,it,expect,vi} from 'vitest';
const mocks=vi.hoisted(()=>({put:vi.fn(),acquire:vi.fn(),release:vi.fn()}));
vi.mock('../src/pg-edit-session.js',()=>({acquirePgScopeAccessLease:mocks.acquire,releasePgScopeAccessLease:mocks.release,resolvePgEditWorkspaceContext:s=>({workspaceId:s.workspaceId,baseUrl:'http://tower',appNpub:'app'})}));
vi.mock('../src/tower-command-intents.js',()=>({putTowerPgScopeAccess:mocks.put}));
vi.mock('../src/pg-read-hydrator.js',()=>({resolveTowerPgWorkspaceContext:s=>({workspaceId:s.workspaceId,baseUrl:'http://tower',appNpub:'app'})}));
import {scopeAccessManagerMixin as mixin,SCOPE_ACCESS_ROLES} from '../src/scope-access-manager.js';
function store() {const s={...mixin,workspaceId:'workspace',isTowerPgMode:true,pgWorkspaceMembers:[{actor_id:'human',kind:'human',display_name:'Pete'},{actor_id:'agent',kind:'agent',display_name:'Rick'}],pgChannelGrantGroupOptions:[{groupId:'group',label:'Builders'}],getPgWorkspaceMemberLabel:m=>m.display_name,getTowerSyncService:()=>({ensureLoaded:vi.fn(async()=>({can_manage:true,revision:'v1',grants:[],effective_access:[]}))})};Object.defineProperty(s,'scopeAccessVisible',{get:()=>Object.getOwnPropertyDescriptor(mixin,'scopeAccessVisible').get.call(s)});Object.defineProperty(s,'scopeAccessPrincipalOptions',{get:()=>Object.getOwnPropertyDescriptor(mixin,'scopeAccessPrincipalOptions').get.call(s)});return s;}
describe('Scope Access',()=>{
 it('offers stable people, agents and canonical groups with distinct roles',()=>{const s=store();s.scopeAccessPrincipalKind='human';expect(s.scopeAccessPrincipalOptions).toEqual([{id:'human',label:'Pete'}]);s.scopeAccessPrincipalKind='agent';expect(s.scopeAccessPrincipalOptions).toEqual([{id:'agent',label:'Rick'}]);s.scopeAccessPrincipalKind='group';expect(s.scopeAccessPrincipalOptions).toEqual([{id:'group',label:'Builders'}]);expect(SCOPE_ACCESS_ROLES.map(r=>r.label)).toEqual(['Context editor','Scope manager']);});
 it('uses management-only canonical choices without extra directory authority',()=>{const s=store();s.scopeAccessData={principals:{actors:[{id:'scoped-agent',kind:'agent',label:'Scoped agent'}],groups:[{id:'builders',label:'Builders'}]}};s.scopeAccessPrincipalKind='agent';expect(s.scopeAccessPrincipalOptions).toEqual([{id:'scoped-agent',kind:'agent',label:'Scoped agent'}]);s.scopeAccessPrincipalKind='group';expect(s.scopeAccessPrincipalOptions).toEqual([{id:'builders',label:'Builders'}]);});
 it('uses current revision and scope lease; reader cannot issue commands',async()=>{const s=store();s.scopeAccessScope={record_id:'scope'};s.scopeAccessWorkspaceId='workspace';s.scopeAccessData={can_manage:false};await s.saveScopeAccess();expect(mocks.put).not.toHaveBeenCalled();s.scopeAccessData={can_manage:true,revision:'rev'};s.scopeAccessPrincipalId='agent';s.scopeAccessPrincipalKind='agent';mocks.acquire.mockResolvedValue({id:'lease',lease_token:'token'});mocks.release.mockResolvedValue(undefined);mocks.put.mockResolvedValue({can_manage:true,revision:'new'});await s.saveScopeAccess();expect(mocks.put).toHaveBeenCalledWith(s,'workspace','scope',expect.objectContaining({principal_type:'actor',principal_id:'agent',role:'context_editor',expected_revision:'rev',lease_token:'token'}),expect.any(Object));expect(mocks.release).toHaveBeenCalled();});
 it('surfaces conflict without claiming save and releases lease',async()=>{mocks.put.mockRejectedValue({status:409});const s=store();s.scopeAccessScope={record_id:'scope'};s.scopeAccessWorkspaceId='workspace';s.scopeAccessData={can_manage:true,revision:'rev'};s.scopeAccessPrincipalId='human';await s.saveScopeAccess();expect(s.scopeAccessError).toContain('Refresh');expect(s.scopeAccessNotice).toBe('');});
});
